### ISSUE TITLE
Does Rock support query groups?

### ISSUE THREAD

**Issue by michaelmesser** [ollef/rock#5]
https://salsa-rs.github.io/salsa/plumbing/query_groups.html
Rust's Salsa supports query groups. Can something similar be easily done with Rock?

**Comment by ollef** [comment]
After checking that page I still don't know what query groups are. Can you explain?

**Comment by michaelmesser** [comment]
This link has a clearer explanation. https://rustc-dev-guide.rust-lang.org/salsa.html#query-groups

**Comment by ollef** [comment]
I'm still not sure I understand completely, but here's a way to make more modular queries and rules:

```haskell
{-# language GADTs #-}

import Rock

data Subquery a where
  SQ :: Subquery Int

subrules :: Rules Subquery
subrules SQ = pure 610

data Query a where
  Subquery :: Subquery a -> Query a
  Query :: Query Int

rules :: Rules Query
rules (Subquery sq) = transFetch (fetch . Subquery) $ subrules sq
rules Query = pure 611
```

In this example, `Subquery` and `subrules` are independent from `Query` and `rules`.

If there are more complex dependencies between modules, e.g. some rudimentary queries that are used in many submodules, you could use "capability classes". Here's an example:

```haskell
{-# language GADTs #-}

import Rock

data Subquery1 a where
  SQ1 :: Subquery1 Int

data Subquery2 a where
  SQ2 :: Subquery2 Int

class HasSubquery1 q where
  subquery1 :: Subquery1 a -> q a

class HasSubquery2 q where
  subquery2 :: Subquery2 a -> q a

subrules1 :: GenRules Subquery1 q
subrules1 SQ1 = pure 610

subrules2 :: HasSubquery1 q => GenRules Subquery2 q
subrules2 SQ2 = fetch $ subquery1 SQ1

data Query a where
  Subquery1 :: Subquery1 a -> Query a
  Subquery2 :: Subquery2 a -> Query a
  Query :: Query Int

instance HasSubquery1 Query where
  subquery1 = Subquery1

instance HasSubquery2 Query where
  subquery2 = Subquery2

rules :: Rules Query
rules (Subquery1 sq) = subrules1 sq
rules (Subquery2 sq) = subrules2 sq
rules Query = pure 611
```

Do you think this covers the use cases of Salsa's query groups?

**Comment by michaelmesser** [comment]
Yes. Thank you.
